### ISSUE TITLE
Work on Scaling of k8 cluster to handle more jmeter pods

### ISSUE THREAD

**Issue by dpatel7** [k8-proxy/p-k8-jmeter-test-engine#41] opened 2020-10-07 08:45 UTC

**Comment by dpatel7** [comment] 2020-10-07 13:35
@upworkroozbeh What we want you to do in this issue is to look for solution how we can handle more nodes to generate 100k threads. The current jmeter image is processing 100 threads each so technically we will need 1000 pods running in cluster. what we are after is define outline of what node sizes require to handle those pods with minimum startup time. also need to have some costing table to understand cost of those running table.

**Comment by uzfarid** [comment] 2020-10-12 08:13
@upworkroozbeh, @dpatel7  should we have some review call today?

**Comment by uzfarid** [comment] 2020-10-17 05:09
seems this is duplicate of this https://github.com/k8-proxy/p-k8-jmeter-test-engine/issues/73. will assign this ticket to Harut also. we will close one of them

**Closed** 2020-10-23 14:01 UTC
Labels: P1
